name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install spdlog
      run: sudo apt-get install libspdlog-dev
    - name: install Boost
      run: sudo apt-get install libboost-all-dev
    - name: install libpqxx-dev
       run: sudo apt-get install libpqxx-dev
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
